export const GET_BOARD = "GET_BOARD";
export const SET_COLUMN_ORDER = "SET_COLUMN_ORDER";
export const SET_TASK_IN_SAME_COLUMN = "SET_TASK_IN_SAME_COLUMN";
export const SET_TASK_IN_NEW_COLUMN = "SET_TASK_IN_NEW_COLUMN";
export const SET_COLUMN_TITLE = "SET_COLUMN_TITLE";
